version: "3.8"

services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    env_file:
      - ./stack.env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - proxy-network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: qloapps:latest
    depends_on:
      - db
    restart: unless-stopped
    expose:
      - "80"
    env_file:
      - ./stack.env
    environment:
      DB_HOST:     "db"
      DB_NAME:     "${MYSQL_DATABASE}"
      DB_USER:     "${MYSQL_USER}"
      DB_PASSWORD: "${MYSQL_PASSWORD}"
    networks:
      - proxy-network

volumes:
  db_data:

networks:
  proxy-network:
    external: true
