version: "3.8"

services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    env_file:
      - ./stack.env
    volumes:
      - db_data_test:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    networks:
      - internal-network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: qloapps:latest
    depends_on:
      - db
    restart: unless-stopped
    expose:
      - "80"
    env_file:
      - ./stack.env
    environment:
      DB_HOST: db
      DB_NAME: "${MYSQL_DATABASE}"
      DB_USER: "${MYSQL_USER}"
      DB_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - web_data_test:/var/www/html
    networks:
      - internal-network
      - proxy-network

volumes:
  db_data_test:
  web_data_test:

networks:
  internal-network: {}
  proxy-network:
    external: true
