version: "3.8"

services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    env_file:
      - ./stack.env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - internal-network

  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # sorgt dafür, dass /admin zu /login wird
        ADMIN_DIR: "login"
    restart: unless-stopped
    depends_on:
      - db
    expose:
      - "80"
    env_file:
      - ./stack.env
    environment:
      DB_HOST:     db
      DB_NAME:     "${MYSQL_DATABASE}"
      DB_USER:     "${MYSQL_USER}"
      DB_PASSWORD: "${MYSQL_PASSWORD}"
    networks:
      - internal-network
      - proxy-network
    volumes:
      # 1) Persistiere nur das Config-Verzeichnis,
      #    damit settings.inc.php erhalten bleibt
      - qloapps_config:/var/www/html/config
      # 2) Optional: Persistiere Bilder & Uploads
      - qloapps_img:/var/www/html/img
      # 3) Optional: Persistiere Cache & Logs
      - qloapps_var:/var/www/html/var

volumes:
  db_data:
  qloapps_config:
  qloapps_img:
  qloapps_var:

networks:
  internal-network:
    name: ${COMPOSE_PROJECT_NAME}_internal-network
    driver: bridge
  proxy-network:
    external: true
